version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MARIADB_DATABASE: wordpress
      MARIADB_USER: ${MYSQL_USER}
      MARIADB_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: always
    # 포트 80 삭제 (NPM이 대신 관리할 거라 직접 노출 안 함)
    expose:
      - "80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  # SSL 및 도메인 관리를 위한 도구 추가
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    ports:
      - '80:80'    # HTTP
      - '443:443'  # HTTPS
      - '81:81'    # 관리 화면 포트
    volumes:
      - ./npm/data:/data
      - ./npm/letsencrypt:/etc/letsencrypt

volumes:
  db_data: